# Generated by Django 6.0.1 on 2026-01-31 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_dailyreport_unique_together_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='merchandiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='stores_visited',
            field=models.ManyToManyField(blank=True, related_name='daily_reports', to='stores.store'),
        ),
    ]
