# Generated by Django 6.0.1 on 2026-02-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_amount_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='merchandiser',
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
